Code refactoring
AjroudiRida/school-library pull request #5
Opened 2023-10-16 15:43 UTC by AjroudiRida

In this featured branch, my partner and me did the following:
- Make sure YAGNI, KISS, and DRY rules and Ruby style guide are respected.
- Follow SOLID principles.

2023-10-16 15:56 UTC, zeff96 reviewed
### Status: CHANGES REQUIRED ♻️ ♻️ ♻️ 
Hi @AjroudiRida and @MozamelJawad , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media1.giphy.com/media/W3dGGNpaeOt3KcUWr2/200w.webp?cid=ecf05e47sgr4h7a7zo4bhs9qf0bkzp0858fqg0a69uf1o9uy&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
✔️ Linters passing
✔️ Correct GitFlow
✔️ Descriptive pull request


## Required Changes ♻️

- [x] Hello, am going to leave comments for all changes that are required in the app.rb file because I can't find a suitable place to leave the comments

- 🎓👨‍🏫👩‍🏫 To follow the single responsibility principle effectively, the calls to create instances of the Teacher and Student classes, which both inherit from the Person class, should be consolidated within the create_person method. 🧐 This method has the exclusive responsibility of crafting either a teacher or a student object, making our code more organized and adherent to the principle. 🛠️ It's all about keeping things neat and efficient! 💡😊
- 📜🚀 The project requirements designated the main.rb file with the primary role of initiating the program and prompting the user for their initial choices or the option to quit. However, I've noticed that in your implementation, the user input requests and validation checks are placed in the app.rb file. To maintain a clear adherence to the single responsibility principle, it's advisable to centralize these user interactions within the main.rb file. 🔄 This separation of responsibilities ensures that each part of your program has a well-defined role, promoting better code organization and maintainability. 🧐✅

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-17 07:51 UTC, MozamelJawad commented
Hi @zeff96, thanks for your review, If you kindly give your comments on app.rb file.

2023-10-17 07:57 UTC, zeff96 commented
Hi @MozamelJawad, I wanted to give  review on app.rb but unfortunately there were no changes you made to that file so it was not accessible to me during the review on the files changed tab, that is where we perform reviews

2023-10-17 08:01 UTC, AjroudiRida commented
Hello! @zeff96 i think app.rb is okay and follow the project requirement, please write your review here in github comment section

2023-10-17 08:06 UTC, zeff96 commented
Hello @AjroudiRida, kindly have a look at the following bad examples and compare with app.rb and see if there is any similarity

```sh
# *Bad example of Single responsability rule
  # if you see this Remind them about the Best practices and Solid lesson: https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid
  def create_person
    # *all requests for input and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input.
    print "Do you want to create a student (1) or a teacher (2)? [Input the number]: "
    person_type = gets.chomp

    if person_type != "1" && person_type != "2"
      puts "Invalid option"
      return
    end
    
    print "Age: "
    age = gets.chomp

    print "Name: "
    name = gets.chomp
    
    person =
      if person_type == "1"
        create_student(age, name)
      elsif person_type == "2"
        create_teacher(age, name)
      end

    @people << person
    puts "Person created successfully"
  end

```ruby
 # *Bad example of Single responsability rule, this is also a
  # *Bad example of YAGNI and KISS as the contents fo this method could've been placed somewhere else
  # if you see this Remind them about the Best practices and Solid lesson: https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid
  def create_student(age, name)
    # *all requests for input and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input.
    print "Has parent permission? [Y/N]: "
    parent_permission = gets.chomp
    parent_permission = parent_permission.downcase == "y"
    
    # *this line should've been placed in the 'create_person()' method
    Student.new(age, name, parent_permission)
  end
  
  # *Bad example of Single responsability rule, this is also a
  # *Bad example of YAGNI and KISS as the contents fo this method could've been placed somewhere else
  # if you see this Remind them about the Best practices and Solid lesson: https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid
  def create_teacher(age, name)
    # *all requests for input and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input.
    print "Specialization: "
    specialization = gets.chomp
    
    # *this line should've been placed in the 'create_person()' method
    Teacher.new(age, specialization, name)
  end
```

2023-10-17 08:11 UTC, zeff96 commented
Hello @AjroudiRida and @MozamelJawad, does it make sense to you know?

2023-10-17 08:12 UTC, AjroudiRida commented
@zeff96 just one question the project requirement mentioned that the changes must be done on main.rb? right?

2023-10-17 08:16 UTC, zeff96 commented
@AjroudiRida, According to the project , initially app was within main.rb, has been placed in another file and refactored but since you had app.rb already. all you had to do was to refactor app.rb to the said principles

2023-10-17 08:28 UTC, zeff96 commented
@AjroudiRida, You app.rb file is good, all you need to change is either create classes or methods that has a sole responsibility of requesting user inputs and validations and move instanciation of  Teacher.new and Student.new to create_person method

2023-10-17 09:19 UTC, Efiamotu-1 requested changes
Hi @AjroudiRida & @MozamelJawad , 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-17 09:19 UTC, Efiamotu-1 commented on handle_invalid_option.rb
- @AjroudiRida & @MozamelJawad as requested by the previous reviewer in your `app.rb` file your codebase is not following the `Single Responsibility Rule`
- [ ] To follow the `Single Responsibility Rule` for best practices all requests for input and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input. see the example code snippet below
- code snippets
```ruby
    print "Do you want to create a student (1) or a teacher (2)? [Input the number]: "
    person_type = gets.chomp

    print 'Title?'
    title = gets.chomp

    print 'Author?'
    author = gets.chomp
```
- [ ] Please kindly update your code base to follow this rule by implementing the above requirement everywhere in your app where you are requesting for user inputs :+1: :sparkles:

2023-10-17 09:19 UTC, Efiamotu-1 commented on handle_invalid_option.rb
- 
- [ ] Following the previous reviewers request, this below line of code in your create_student method should've been placed in the `create_a_person()` method in your `app.rb` file
```ruby
student = Student.new(classroom, age, name, parent_permission)
    @people << student
```

2023-10-17 09:19 UTC, Efiamotu-1 commented on handle_invalid_option.rb
- 
- [ ] Following the previous reviewers request, this below line of code in your create_teacher method should've been placed in the `create_a_person()` method in your `app.rb` file
```ruby
teacher = Teacher.new(specialisation, age, name)
    @people << teacher
```

2023-10-17 09:28 UTC, AjroudiRida commented on handle_invalid_option.rb
@Efiamotu-1 it was included previously but because of linters i was forced to take it out , i will disable the linter rule and make it again like it was before

2023-10-17 15:39 UTC, julie-ify approved these changes
Hi @AjroudiRida an d @MozamelJawad, 

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-17 16:01 UTC, merged